version: '3.3'

services: 
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=social_app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_PORT=8091
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data